### ISSUE TITLE
observer meta issue

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#1000]
I am opening this to collect all known problem with the observer branch of dom-text-mapper / annotator / hypothes.is.

So, things to solve before integration:

 - [x] https://github.com/hypothesis/h/issues/971 - " DOM changes vs. Editor" 
 - [x] https://github.com/hypothesis/dom-text-mapper/issues/27 - "sporadic crash in _alterAncestorsMappingData()" 
 - [x] https://github.com/hypothesis/h/issues/994 - "some pages can kill the MutationSummary library"
 - [x] https://github.com/hypothesis/h/issues/1022 - "annotation cards not updated in the sidebar"
 - [ ] https://github.com/hypothesis/annotator/issues/38 - "Sometimes the browser just 
gets fed up, and stops the JS engine" - *Probably some memory leak in mutation-summary or dom-text-mapper or annotator or h. We need to debug this.*
 - [x] https://github.com/hypothesis/dom-text-mapper/issues/28 - "Change dom-text-mapper's query API to async"
 - [x] https://github.com/hypothesis/annotator/issues/45 - "Annotator: Move to d-t-m's new async API"
 - [x] https://github.com/hypothesis/dom-text-mapper/issues/30 - dom-text-mapper: "unbreak page_text_mapper_core" (required for PDF)
 - [x] https://github.com/hypothesis/annotator/issues/41 - "make PDF work again" - *I'll do this one, too.*
 - [x] https://github.com/hypothesis/dom-text-mapper/issues/31  - "problems with consistent state of pdf-text-mapper" 
 - [x] https://github.com/hypothesis/h/issues/1035 - "Selection shown is not what was selected"
 - [ ] https://github.com/hypothesis/h/issues/1049 - "Can't open sidebar on this page"
 - [ ] https://github.com/hypothesis/h/issues/1050 - "Problems with eBay"
 - [ ] https://github.com/hypothesis/h/issues/1051 - "Cannot get adder on the guardian"
 - [ ] Make sure [this page](http://nautil.us/issue/1/what-makes-you-so-special/metaphors-are-us) works properly. (See #1013 for details.)

One more (optional) issue to solve, but I think we can postpone it to after first release:

 - [ ] https://github.com/hypothesis/annotator/issues/20 - "dealing with removed and re-added highlights"

**Comment by gergely-ujvari** [comment]
@csillag: What should we do with this issue?

**Comment by tilgovi** [comment]
This issue feels a bit stale at this point. Closing.
