### ISSUE TITLE
Problems with Annotation.uri meta-issue

### ISSUE THREAD

**Issue by gergely-ujvari** [hypothesis/h#1244]
I am creating this issue to collect all previous issues which have the same root cause: The saved annotation.uri field is not good enough, and visiting a page does not always load back all relevant annotations. 

This is a recurring problem so I'm suggesting this issue to be a requirement for our 0.2 milestone.

We have more than one open issue for this topic
- Concrete sites
  - [ ] #1242 (JEP)
  - [ ] #977 NYTimes rel=canonical mismatches mean mobile doesn't see desktop annotations.
- Related issues
  - [ ] #1090 Discard URL fragments when requesting annotations for a page
  - [ ] #1030 Linking HTTP and HTTPS targets as equivalent
- Issues that could improve the situation
  - [ ] #834 cross-format: new uri notifications upon discovering equivalences
  - [x] #833 cross-format: recursive search for equivalences
- Other things to consider (no open issue for them)
  - [ ] We don't recognize uris as equivalent if query parameters are present. This is related to #833 because changing a query parameter can change the content (but not always)
  - [x] We do not use the found canonical uris for saving the annotations, but only for our search queries.
  - [ ] We have bogus annotation mapping in the backend, I think if the annotation.target.source field exists it shadows the real annotation.uri field. This has to be sorted out.

Suggested plan of action:
- [ ] Implement #1090 Discard URL fragments when requesting annotations for a page
- [ ] Implement #1030 Linking HTTP and HTTPS targets as equivalent
- Change what we save for annotation.uri
  - [x] If canonical URL is given use this instead of the actual uri, this way our life will be much simpler
  - If canonical URL is not given, then we have no other choice but to save the actual uri.
- [x] Implement #833 cross-format: recursive search for equivalences
- [ ] Implement at least a simple version of https://github.com/hypothesis/hypothesis.github.io/issues/8 to verify suspected equivalencies. 

Your suggestions?
