### ISSUE TITLE
Move to Python 3

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5384]
Run h in Python 3 only (no support for 2.7) in dev envs, CI and QA and production.

[Python 2 is supported through next year](https://pythonclock.org/) (2019), but there are [lots of Python libraries dropping support for 2 before then](https://python3statement.org/) so we do need to be making progress in the right direction.

If a library we're using drops support for Python 2 then we won't be able to upgrade to the new, non-Python-2-supporting version of that library without upgrading to Python 3 first. We will of course still be able to keep using the old version of the library and since we don't yet regularly keep h's dependencies up to date we wouldn't even notice immediately. Still, we could end up needing to upgrade a dependency to get a bug fix or security fix but be unable to do so because the fixed version requires Python 3. And of course we don't want to still be on Python 2 in 2020 when Python 2 itself is no longer supported by the Python maintainers.

I want to try and do this without causing any disruption and to use the opportunity to get some improvements in place that will both be long-term improvements and make the transition to Python 3 smoother.

### Dev envs

- [x] Run all h dev env stuff in tox so that the Python version that the dev server and tests etc run in is now in `tox.ini` so we can move everyone's dev servers to 3 by merging a `tox.ini` change

### Monitoring

- [x] ~~<https://github.com/hypothesis/h/issues/5514>: Fix all unresolved Sentry issues for h, so that there's no Sentry noise and any new issues caused by Python 3 can be spotted. For issues that aren't reasonable to fix using Sentry's <samp>Ignore</samp> button is fine.~~ _Update: There is still work to do here, but it is not longer a pre-Python 3 task_.

### Specific things that've been noticed and may need to be fixed

- [x] Replace any real uses of `xrange` (the actual one, not `h._compat.xrange`) with `range`.

- [x] <https://github.com/hypothesis/h/issues/5515>: Look at usages of `ascii`, `map`, `filter`, `hex`, `oct` and `zip`.

### Dependencies

- [x] <https://github.com/hypothesis/h/issues/5516>: Investigate `deform-jinja2` Python 3 compatibility.
- [x] [Upgrade `pyramid_tm`](https://github.com/hypothesis/h/pull/5644#issuecomment-503517112)
  Card: <https://github.com/hypothesis/h/issues/5646>

### Linting

- [ ] <https://github.com/hypothesis/h/issues/5517>: Review PyLint warnings for Python 3 problems, fix them, and run PyLint on Travis (with only the Python 3 warnings enabled) so that they stay fixed

### 2-to-3 tools

- [x] <https://github.com/hypothesis/h/issues/5518>: Review Python 3 test warnings from Python 2.7's `-3` flag

- [x] <https://github.com/hypothesis/h/issues/5519>: Convert Python 2 code to Python 2/3 compatible with futurize

- [x] <del><https://github.com/hypothesis/h/issues/5520>: Add all future imports and use flake8-future-import to enforce them</del>

- [x] <https://github.com/hypothesis/h/issues/5521>: Run 2to3 and make or deliberately decide to ignore all its changes

- [x] <https://github.com/hypothesis/h/issues/5522>: Run modernize

## Actually enacting the move to Python 3

- [x] Change Docker image to run h in Python 3. Here's an old and possibly out of date PR that does this: https://github.com/hypothesis/h/pull/4901/files
- [x] Change `tox.ini`, `Makefile`, `.travis.yml` and `Jenkinsfile` to run h in Python 3 only in dev and CI. For example when running the dev server, or when running tests.

## Post Python 3 clean up tasks

- [x] Enable Dependabot for h, as we have to bouncer and LMS, start upgrading all of h's Python dependencies to the latest versions and keeping them there.
- [x] Remove _compat.py. (First need to replace uses of each `_compat.py` feature with the plain Python 3 version throughout the code.) https://github.com/hypothesis/h/issues/5714
- [x] Remove now-redundant `__future__` imports: `2to3 -f future h tests`. https://github.com/hypothesis/h/issues/5715
- [x] Generally run `2to3` and make all Python 2-incompatible changes that it suggests that we didn't want to make earlier because they're Python 2-incompatible. https://github.com/hypothesis/h/pull/5740
- [x] Update and test developer install docs
- [x] Remove no-longer-neccessary explicitly inheriting from `object` https://github.com/hypothesis/h/issues/5716
- [x] Replace uses of `set()` with set literals (`2to3 -nw -f set_literal h tests`) https://github.com/hypothesis/h/issues/5717
- [x] Remove `encode_headers_tween_factory` and `native_string` matcher, these shouldn't be needed anymore https://github.com/hypothesis/h/issues/5718
 - [x] Remove `str()` calls that exist for py2 compat, e.g. https://github.com/hypothesis/h/pull/4962/commits/f84bc84f3f281ad6e0471e321606956297e7dae2 https://github.com/hypothesis/h/issues/5719
- [x] Replace the third-party mock library with the builtin unittest.mock https://github.com/hypothesis/h/issues/5720

**Comment by robertknight** [comment]
> Fix all unresolved Sentry issues for h, so that there's no Sentry noise and any new issues caused by Python 3 can be spotted. For issues that aren't reasonable to fix using Sentry's Ignore button is fine.

I think we can perhaps say that is out of scope for this epic now given that the move to Python 3 in production has happened? I know you still want the team to resolve outstanding Sentry issues @seanh but it doesn't seem essential to the Python 3 migration any more.

**Comment by robertknight** [comment]
I edited the "Enable Dependabot" item to only refer to Python dependencies. We have security updates already enabled for both JS and Python deps and I think automatically bumping JS dependencies is out of scope for this issue. It is also less important as there is a relatively small amount of JS code in h and we're updating it much less often.

**Comment by robertknight** [comment]
h has been running Python 3.6 in production for over a year so I'm going to close this.
