### ISSUE TITLE
Fix h's Sentry noise

### ISSUE THREAD

**Issue by seanh** [hypothesis/h#5514]
We currently have <del>11</del>4 unresolved production h backend issues in Sentry. This is too many: we don't want any new issues created by upgrading to Python 3 to be drowned out by preexisting noise. Also we just don't want to have a lot of unresolved issues that we're ignoring (broken windows). Let's get these fixed before upgrading to Python 3.

Sentry issues that need to be fixed in prioritized order:

- [ ] Crash when trying to create an annotation: ConcurrentUpdateError: concurrent document creation https://github.com/hypothesis/h/issues/5495
- [ ] Crash when the client is trying to get an OAuth token: AttributeError: 'NoneType' object has no attribute 'userid' https://github.com/hypothesis/h/issues/5280
- [ ] Group page crash (when trying to join a group, looks like) duplicate key value violates unique constraint: IntegrityError https://github.com/hypothesis/h/issues/5551
- [x] /accounts/developer page crash: MultipleResultsFound https://github.com/hypothesis/h/issues/5552
- [ ] [URI normalization crashes when port not an int](https://github.com/hypothesis/h/issues/5605)
- [ ] [Annotation create API crashes on long URLs ](https://github.com/hypothesis/h/issues/5606)
- [x] [WebSocket HandshakeError: HTTP method must be a GET](https://github.com/hypothesis/h/issues/5607)

**Comment by hmstepanek** [comment]
https://github.com/hypothesis/product-backlog/issues/956

**Comment by hmstepanek** [comment]
https://github.com/hypothesis/product-backlog/issues/955

**Comment by hmstepanek** [comment]
https://github.com/hypothesis/product-backlog/issues/964

**Comment by hmstepanek** [comment]
https://github.com/hypothesis/product-backlog/issues/965

**Comment by hmstepanek** [comment]
https://github.com/hypothesis/product-backlog/issues/967

**Comment by seanh** [comment]
The Sentry issue for the [handling long claimant URIs issue](https://github.com/hypothesis/h/issues/5552) seems to have been [automatically resolved by Sentry due to inactivity](https://sentry.io/organizations/hypothesis/issues/864120830/activity/) ("Sentry marked this issue as resolved due to inactivity") which I didn't realise Sentry did.

**Comment by seanh** [comment]
@hmstepanek I've updated this issue to reflect the four remaining issues we're currently seeing in Sentry. As commented above it looks like at least one issue might have been automatically resolved by Sentry though it remains an issue in the code. But as long as it doesn't reappear in Sentry I'm happy to ignore it! So let's just focus on fixing these four now

**Comment by hmstepanek** [comment]
I imagine it’s probably inactive because the user figured out they couldn’t annotate any of those urls so they stopped trying.

**Comment by leedenison** [comment]
Obsolete.
