### ISSUE TITLE
Enable consistent configuration parameters from LMS -> Via and Via 3 

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/h#5975]
### Problem

New configuration parameters have been introduced recently and more are on the way. To keep LMS, Via and Via 3 all in sync with the changes we are going to ensure that the names map cleanly across the products without each having to be changed to handle it.

For example the following parameters to Via:

* `via.request_config_from_frame`
* `via.config_frame_ancestor_level`

Result in the following configuration to H:

```{
    "requestConfigFromFrame": {
        "origin": ...,
        "ancestorLevel": ...
    }
}
```

### Solution

To simplify this all `h` parameters to `via` will now be under `via.h.*` and the names will be directly mapped from snake to camel case.

For example the two parameters above will now be:

 * `via.h.request_config_from_frame.origin`
 * `via.h.request_config_from_frame.ancestor_level`

### Implementation plan

 * [ ] Delegate casting of configuration types to client
 * [ ] Add parsing to Via 3, with backwards compatibility
 * [ ] Copy parsing to Via, with backwards compatibility
 * [ ] Move LMS to calling with new style
 * [ ] Remove backwards compatibility in:
   * [ ] Via 3
   * [ ] Via
   * [ ] H
