### ISSUE TITLE
Meta-issue for PDF support

### ISSUE THREAD

**Issue by csillag** [hypothesis/h#758]
This is an issue to coordinate / consolidate our PDF-related efforts. Tasks:
- [x] Check if PDF.js can be shipped with the Chrome extension - See #512, also #288 
- [x] Fix PDF.js support by closer integration and a new anchoring approach - See #757
- [x] Fix #430 (if it's not automatically covered by the above steps)
