### ISSUE TITLE
Store LMS metadata for annotations

### ISSUE THREAD

**Issue by marcospri** [hypothesis/h#8123]
### New serial primary key 

- [x] Add new nullable `pk` column and a new sequence
- [x] Create task to fill the values for `pk` in batches
- [x] Call the new task from h-periodic
- [ ] Wait for most rows to have a value
- [ ] Use the new sequence as the default value for new rows
- [ ] Make the `pk` the actual primary key of the table
- [ ] Optional. Rename the existing `id` to `guid` or `pubid` and the new `pkd` to `id`.

### New annotation_metadata table

- [x] Create the new `annotation_metadata`, using a FK to the new `annotation.pk` table.

### API POST

- [ ] Accept metadata for annotations as a JWE for creating and editing annotations
- [ ] Limit the metata keys to the known values 

### LMS forward metadata

- [ ] Include a new config option in JSConfig to expose the metadata, encode it as a JWE
- [ ] Forward the metadata from the LMS frontend to the client
- [ ] Forward the metadata from the client to H.

----
## TODO

- [ ] Create indexes on metadata
